---
title: "R Notebook"
output: html_notebook
---



```{r}
Data <- read.csv(file = 'C:/Users/User/OneDrive - Georgia Institute of Technology/Desktop/MGT6203/SQL_Output.csv',  fileEncoding="UTF-8-BOM")
head(Data)
```

```{r}
Data <- subset(Data, select = -c(Model, Group, TASP, Cluster, CondoComplex, CondoComplexName, 
                                 PARCEL, ABSTRPRD, XTRAFFIC, COMMUSE, NETPRICE, DEDUCT, QUALIFIED, 
                                 NBHD, SMONTH, SYEAR, NBHD_Name_Sales, NBHD_Name_Crime.1,
                                 FINBSMNT, BASEMENT, QUALITY, STORIES, NOCARS, FLOORLVL, ARCSTYLE,
                                 TOTUNITS, NBHD_No, NBHD_Name_Crime, GARTYPE, STATUS, CONDITION))
```

```{r - Show unique crime categories}
unique(Data$OFFENSE_CATEGORY)
```

```{r}
#mutate offense categories in separate columns
Data <- Data %>%
  mutate("auto_theft" = ifelse(OFFENSE_CATEGORY == "auto theft",Count,0)) %>%
  mutate("sexual_assault" = ifelse(OFFENSE_CATEGORY == "sexual assault",Count,0)) %>%
  mutate("other_crimes_against_persons" = ifelse(OFFENSE_CATEGORY == "other crimes against persons",Count,0)) %>%
  mutate("all_other_crimes" = ifelse(OFFENSE_CATEGORY == "all other crimes",Count,0)) %>%
  mutate("drug_alcohol" = ifelse(OFFENSE_CATEGORY == "drug alcohol",Count,0)) %>%
  mutate("larceny" = ifelse(OFFENSE_CATEGORY == "larceny",Count,0)) %>%
  mutate("aggravated_assault" = ifelse(OFFENSE_CATEGORY == "aggravated assault",Count,0)) %>%
  mutate("theft_from_motor_vehicle" = ifelse(OFFENSE_CATEGORY == "theft from motor vehicle",Count,0)) %>%
  mutate("robbery" = ifelse(OFFENSE_CATEGORY == "robbery",Count,0)) %>%
  mutate("burglary" = ifelse(OFFENSE_CATEGORY == "burglary",Count,0)) %>%
  mutate("public_disorder" = ifelse(OFFENSE_CATEGORY == "public disorder",Count,0)) %>%
  mutate("white_collar_crime" = ifelse(OFFENSE_CATEGORY == "white collar crime",Count,0)) %>%
  mutate("arson" = ifelse(OFFENSE_CATEGORY == "arson",Count,0)) %>%
  mutate("murder" = ifelse(OFFENSE_CATEGORY == "murder",Count,0))
```

```{r}
#Delete Count and Offense Category columns
Data <- subset(Data, select = -c(Count, OFFENSE_CATEGORY))
```

```{r}
Data <- Data %>% group_by(SN, YRBUILT, NUMBDRM, NUMBATHS, LIVEAREA, SPRICE, Month, Year) %>% 
  summarise('auto_theft' = sum(auto_theft), 'sexual_assault' = sum(sexual_assault),
            'other_crimes_against_persons' = sum(other_crimes_against_persons), 'all_other_crimes' = sum(all_other_crimes),
            'drug_alcohol' = sum(drug_alcohol), 'larceny' = sum(larceny),
            'aggravated_assault' = sum(aggravated_assault), 'theft_from_motor_vehicle' = sum(theft_from_motor_vehicle),
            'public_disorder' = sum(public_disorder), 'burglary' = sum(burglary),
            'white_collar_crime' = sum(white_collar_crime), 'arson' = sum(arson),
            'murder' = sum(murder),.groups = 'keep')
```

```{r}
#Drop SN column
Data <- subset(Data, select = -c(SN))
```

```{r - Show all dataframe features}
colnames(Data)
```

```{r}
head(Data)
```

```{r}
#remove duplicates
Data <- Data[!duplicated(Data), ]
```

```{r}
#Look for houses built in year 0
unique(Data$YRBUILT)
```

```{r}
min(Data$YRBUILT)
max(Data$YRBUILT)
```

```{r - Chack for data points built in year 0 & 2013}
filter(Data, YRBUILT == 2013)
filter(Data, YRBUILT == 0)
```


```{r}
#Delete all data points with YRBUILT == 0 or 2013
Data <- filter(Data, YRBUILT != 0)
Data <- filter(Data, YRBUILT != 2013)
unique(Data$YRBUILT)
```
```{r}
min(Data$LIVEAREA)
sort(Data$LIVEAREA)[1:10]
max(Data$LIVEAREA)
```
```{r}
filter(Data, LIVEAREA == 1)
filter(Data, LIVEAREA == 9)
```
```{r}
Data <- filter(Data, LIVEAREA != 1)
Data <- filter(Data, LIVEAREA != 9)
sort(Data$LIVEAREA)[1:10]
```
```{r}
unique(Data$NUMBDRM)
```
```{r}
filter(Data, NUMBDRM == "NULL")

```
```{r}
Data <- filter(Data, NUMBDRM != "NULL")
```

```{r}
unique(Data$NUMBATHS)
```
```{r}
unique(Data$Year)
```
```{r}
typeof(Data$NUMBATHS)
typeof(Data$NUMBDRM)
```
```{r}
Data$NUMBATHS <- as.integer(Data$NUMBATHS)
Data$NUMBDRM <- as.integer(Data$NUMBDRM) 
```

```{r}
head(Data)
```


```{r}
write.csv(Data, "C:\\Users\\User\\OneDrive - Georgia Institute of Technology\\Desktop\\MGT6203\\Clean_data_1.csv", row.names=FALSE)
```